In [1]:
import pandas as pd
import glob
import numpy as np
import re
path = r'D:\JUPYTER\CODIGO_REQUERIMIENTOS\mercadolibre_v4\input\2022S2' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, encoding='utf-8',sep='|', on_bad_lines='skip')
    df["Plataforma"] = "Mercado Libre"  
    if "Dic" in filename:
        df["Periodo"]=202212
    elif "Nov" in filename:
        df["Periodo"]=202211
    elif "Oct" in filename:
        df["Periodo"]=202210
    elif "Set" in filename:
        df["Periodo"]=202209
    elif "Ago" in filename:
        df["Periodo"]=202208
    elif "Jul" in filename:
        df["Periodo"]=202207
    elif "Jun" in filename:
        df["Periodo"]=202206
    elif "May" in filename:
        df["Periodo"]=202205
    elif "Abr" in filename:
        df["Periodo"]=202204
    elif "Mar" in filename:
        df["Periodo"]=202203
    elif "Feb" in filename:
        df["Periodo"]=202202
    else:
        df["Periodo"]=202201
    li.append(df)

df = pd.concat(li, axis=0, ignore_index=True)

In [2]:
#df  = pd.read_excel("10_11_12_v2_clientesyventas.xlsx",converters={'CUS_PHONE':str,'CUS_EMAIL':str})

In [3]:
df.head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,1546479,ZIP.,NaN,NaN,...,Esculturas,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,8001268,ZIP.,NaN,NaN,...,Suplementos,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Maquillaje,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201

### QUEDARSE SOLO CON LOS NUEVOS

In [4]:
df.shape

(297529, 24)

In [5]:
df = df[df['ITE_ITEM_CONDITION']=='new']

In [6]:
df.shape

(287482, 24)

### CONVERTIR A CADENA EL N. DOCUMENTO

In [7]:
df[(df['CUS_CUST_DOC_TYPE']=='RUC') & (df['CUS_CUST_DOC_NUMBER']!=0)].head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
77,rcourtney530@gmail.com,DEIRLDEIRL,NaN,NaN,D EIRL,RUC,20252067541,ZIP.,NaN,NaN,...,Muebles para el Hogar,Juegos y Sets de Muebles,Juegos de Comedor,609659619,Juego De Comedor Vintage 6 Sillas Env/gratis A...,new,1,1600,Mercado Libre,202201
78,sraleigh083@gmail.com,AJEPERDELORIENTESAAJEPERDE,NaN,NaN,AJEPER DEL ORIENTE SA,RUC,20393177706,ZIP.,NaN,NaN,...,Lavado,Lavadoras y Lavasecadoras,Level 4 Lavadoras y Lavasecadoras,612043158,Lavadora LG Turbowash 3d Wt22bs6h 22 Kg - Negr...,new,1,2100,Mercado Libre,202201
79,stellaeverly12773@gmail.com,ABIMPORTPERUSCRLABIMPORTP,NaN,NaN,AB IMPORT PERU SCRL,RUC,20453774580,ZIP.,NaN,NaN,...,Laptops y Accesorios,Laptops,Level 4 Laptops,609920299,Laptop Gamer Lenovo Legion 5 Pro Ryzen 7 Gefor...,new,1,3400,Mercado Libre,202201
80,bgiana76@gmail.com,ERER5997887,NaN,NaN,ERAS OYOLA ASOCIADOS EIRL,RUC,20487979890,ZIP.,NaN,NaN,...,Laptops y Accesorios,Laptops,Level 4 Laptops,605181255,Macbook Pro 13 2020 M1 8gb Ram 512gb Ssd Env/g...,new,1,5100,Mercado Libre,202201
81,chiristineross@gmail.com,ALONPATEIRLALONPATEIRL,NaN,NaN,ALON PAT EIRL,RUC,20511586365,ZIP.,NaN,NaN,...,TVs,Level 3 TVs,Level 4 Level 3 TVs,614253193,Televisor Samsung 65 Neo Qled 4k Qn65qn90bagxp...,new,1,3500,Mercado Libre,202201

In [8]:
df2 = df.copy()

# convertir todos los dnis, rucs, acelulares

In [48]:
df2['CUS_CUST_DOC_NUMBER'] = df2['CUS_CUST_DOC_NUMBER'].fillna(0).astype('int64',errors='raise') # convert to int the document number
df2.head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,1546479,ZIP.,NaN,NaN,...,Esculturas,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,8001268,ZIP.,NaN,NaN,...,Suplementos,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Maquillaje,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201

In [49]:
#ver RUCs válidos.
df2[(df2['CUS_CUST_DOC_TYPE']=='RUC') & (df2['CUS_CUST_DOC_NUMBER']!=0)].head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
77,rcourtney530@gmail.com,DEIRLDEIRL,NaN,NaN,D EIRL,RUC,20252067541,ZIP.,NaN,NaN,...,Muebles para el Hogar,Juegos y Sets de Muebles,Juegos de Comedor,609659619,Juego De Comedor Vintage 6 Sillas Env/gratis A...,new,1,1600,Mercado Libre,202201
78,sraleigh083@gmail.com,AJEPERDELORIENTESAAJEPERDE,NaN,NaN,AJEPER DEL ORIENTE SA,RUC,20393177706,ZIP.,NaN,NaN,...,Lavado,Lavadoras y Lavasecadoras,Level 4 Lavadoras y Lavasecadoras,612043158,Lavadora LG Turbowash 3d Wt22bs6h 22 Kg - Negr...,new,1,2100,Mercado Libre,202201
79,stellaeverly12773@gmail.com,ABIMPORTPERUSCRLABIMPORTP,NaN,NaN,AB IMPORT PERU SCRL,RUC,20453774580,ZIP.,NaN,NaN,...,Laptops y Accesorios,Laptops,Level 4 Laptops,609920299,Laptop Gamer Lenovo Legion 5 Pro Ryzen 7 Gefor...,new,1,3400,Mercado Libre,202201
80,bgiana76@gmail.com,ERER5997887,NaN,NaN,ERAS OYOLA ASOCIADOS EIRL,RUC,20487979890,ZIP.,NaN,NaN,...,Laptops y Accesorios,Laptops,Level 4 Laptops,605181255,Macbook Pro 13 2020 M1 8gb Ram 512gb Ssd Env/g...,new,1,5100,Mercado Libre,202201
81,chiristineross@gmail.com,ALONPATEIRLALONPATEIRL,NaN,NaN,ALON PAT EIRL,RUC,20511586365,ZIP.,NaN,NaN,...,TVs,Level 3 TVs,Level 4 Level 3 TVs,614253193,Televisor Samsung 65 Neo Qled 4k Qn65qn90bagxp...,new,1,3500,Mercado Libre,202201

In [51]:
#todos aquellos.. números de documentos, menores a 1000, setearlos como 0, es decir, inválidos.
df2.loc[df2.CUS_CUST_DOC_NUMBER < 1000, 'CUS_CUST_DOC_NUMBER'] = 0
df2.head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,1546479,ZIP.,NaN,NaN,...,Esculturas,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,6703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,8001268,ZIP.,NaN,NaN,...,Suplementos,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Maquillaje,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201

In [52]:
#convertir a cadena.
df2['CUS_CUST_DOC_NUMBER'] = df2['CUS_CUST_DOC_NUMBER'].astype(str)

In [53]:
#agregar zeros en caso de ser DNI.
df2['CUS_CUST_DOC_NUMBER'] = df2.apply(lambda x: x['CUS_CUST_DOC_NUMBER'].zfill(8) if x['CUS_CUST_DOC_TYPE']=='DNI' else x['CUS_CUST_DOC_NUMBER'], axis = 1)

In [54]:
df2.head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,01546479,ZIP.,NaN,NaN,...,Esculturas,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,08001268,ZIP.,NaN,NaN,...,Suplementos,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Maquillaje,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201

### CREADO LLAVE DNI/RUC

In [55]:
#excluir todos los que tienen un DNI inválido
df3 = df2.loc[df2.CUS_CUST_DOC_NUMBER!="00000000"]

In [56]:
df3.head()

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L2,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,01546479,ZIP.,NaN,NaN,...,Esculturas,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Otros,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,08001268,ZIP.,NaN,NaN,...,Suplementos,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Maquillaje,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201

### CLEANING PHONES

In [57]:
def normalizar(phone):
    #cambiar a cadena.
    if type(phone) is float:
        if not math.isnan(phone):
            phone =(str)((int)(phone)) 
        else:
            phone = "0"
    else:        
        #eliminar espacios
        phone = phone.replace(" ", "")
        #eliminar #
        phone = phone.replace("#", "")
        #eliminar .
        phone = phone.replace(".", "")
        #eliminar .
        phone = phone.replace("(", "")
        #eliminar .
        phone = phone.replace(")", "")
        #eliminar .
        phone = phone.split("-")[0]
        #eliminar +51
        phone = phone.replace("+51", "")
        #eliminar 051
        phone = phone[3:] if phone[0:3] == "051" else phone
        #eliminar 0051
        phone = phone[4:] if phone[0:4] == "0051" else phone
        #eliminar 0051
        phone = phone[2:] if phone[0:2] == "51" else phone  
        #eliminar 0 ADELANTE
        phone = phone[1:] if phone[0:1] == "0" else phone  
        #eliminar ,
        phone = phone.replace(",","")
    return phone

In [59]:
#convertir a cadena
df3['CEL_LIMPIO'] = df3['CUS_PHONE1'].fillna(0).astype(int).astype(str)

OverflowError: Python int too large to convert to C long

In [60]:
import math
df3['CEL_LIMPIO'] = df3.apply(lambda x: normalizar(x['CUS_PHONE1']) ,axis =1)

D:\Usuarios\dcantorin\AppData\Local\Temp\ipykernel_6776\134818357.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['CEL_LIMPIO'] = df3.apply(lambda x: normalizar(x['CUS_PHONE1']) ,axis =1)

In [61]:
df3['CEL_LIMPIO'] = df3.apply(lambda x: x['CEL_LIMPIO'] if (len(x['CEL_LIMPIO'])==9 and x['CEL_LIMPIO'][0]=='9') else "" ,axis =1)
df3['CEL_LIMPIO'].head()

D:\Usuarios\dcantorin\AppData\Local\Temp\ipykernel_6776\1170522231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['CEL_LIMPIO'] = df3.apply(lambda x: x['CEL_LIMPIO'] if (len(x['CEL_LIMPIO'])==9 and x['CEL_LIMPIO'][0]=='9') else "" ,axis =1)

0
1
2
3
4
Name: CEL_LIMPIO, dtype: object

In [33]:
#df3[["CUS_PHONE","CEL_LIMPIO"]].to_excel("prueba.xlsx")

In [62]:
df3[df3['CUS_CUST_DOC_NUMBER']=='70025425']['CEL_LIMPIO'].value_counts()

             9
988786755    2
947437757    1
Name: CEL_LIMPIO, dtype: int64

In [63]:
df3.head(5)

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo,CEL_LIMPIO
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,01546479,ZIP.,NaN,NaN,...,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201,
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201,
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201,
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,08001268,ZIP.,NaN,NaN,...,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201,
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201,

In [64]:
df3[(df3['CUS_EMAIL'] == 'ml.peru@bluediamondinnovation.com')]

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo,CEL_LIMPIO
11224,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Level 3 Otros,Level 4 Level 3 Otros,443542066,"Fitbit Aria Air -smart Digital Scale- Black, F...",new,1,209,Mercado Libre,202201,
11225,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Soportes y Estabilizadores,Trípodes para Cámaras,443514417,"Combo Gopro Trípode/monopié Negro, Afttm-001",new,4,636,Mercado Libre,202201,
11226,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Drones,Level 4 Drones,605114017,Tello Boost Combo,new,1,719,Mercado Libre,202201,
11227,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Smartwatches,Level 4 Smartwatches,443545139,Smartwatch Fitbit Sense Lunar White/soft Gold ...,new,1,1299,Mercado Libre,202201,
11228,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Lentes,Level 4 Lentes,445363543,Gopro Módulo De Lente Max Para La Hero9 Black,new,1,419,Mercado Libre,202201,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254377,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Laptops,Level 4 Laptops,612075420,Laptop Asus Vivobook K513 Ci5-1135g7 8gb 512gb...,new,1,2999,Mercado Libre,202201,
254378,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Laptops,Level 4 Laptops,614376927,Laptop Rog Strix G15 Ryzen 7 4800h 16gb 512gb ...,new,5,24645,Mercado Libre,202201,
254379,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Impresoras,Level 4 Impresoras,618673674,Brother Dcpt720w Multifunción Inyección De Tin...,new,1,1059,Mercado Libre,202201,
254380,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Switches,Level 4 Switches,607825777,Switch Administrado Cisco Business Cbs350-48p-4x,new,1,1000,Mercado Libre,202201,
254381,ml.peru@bluediamondinnovation.com,BLUE-DIAMOND-PERU,NaN,NaN,AMAZE PERU EIRL,RUC,20606185775,CALLE GERMAN SCHREIBER 276,PE-LMA,LIMA,...,Laptops,Level 4 Laptops,621846249,Laptop Asus Tuf Fa506ihrb Ryzen5 4600h 8gb 512...,new,6,18504,Mercado Libre,202201,

### VALIDAR CORREO ###

In [65]:
def validaremail(email):
    nuevo_email = ""
    if type(email) is float:
        nuevo_email = (str)(email)
    else:
        if  email.find("@") > -1 and email.find(".") > -1:    
           nuevo_email = email
        else: 
           nuevo_email = ""    
    return nuevo_email

In [66]:
df3['CUS_EMAIL'] = df3.apply(lambda x: validaremail(x['CUS_EMAIL']) ,axis =1)

D:\Usuarios\dcantorin\AppData\Local\Temp\ipykernel_6776\3037738130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['CUS_EMAIL'] = df3.apply(lambda x: validaremail(x['CUS_EMAIL']) ,axis =1)

In [67]:
df3['CAT_CATEG_NAME_L1'] = df3['CAT_CATEG_NAME_L1'].astype(str)

D:\Usuarios\dcantorin\AppData\Local\Temp\ipykernel_6776\3387855032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['CAT_CATEG_NAME_L1'] = df3['CAT_CATEG_NAME_L1'].astype(str)

In [68]:
df3.head(5)

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo,CEL_LIMPIO
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,01546479,ZIP.,NaN,NaN,...,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201,
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201,
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201,
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,08001268,ZIP.,NaN,NaN,...,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201,
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201,

In [69]:
df3.head(20)

,CUS_EMAIL,CUS_NICKNAME,CUS_LAST_NAME,CUS_FIRST_NAME,CUS_BRAND_NAME,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,CUS_ADDRESS,CUS_STATE,CUS_CITY,...,CAT_CATEG_NAME_L3,CAT_CATEG_NAME_L4,ITE_ITEM_ID,ITE_ITEM_TITLE,ITE_ITEM_CONDITION,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT,Plataforma,Periodo,CEL_LIMPIO
0,cronos@3dninjaperu.com,LIMACHECCOSIFRESSIA,LIMACHE CCOSI,FRESSIA,NaN,DNI,01546479,ZIP.,NaN,NaN,...,Level 3 Esculturas,Level 4 Level 3 Esculturas,609400669,Coraline Lamp Diorama- Figura Plastica,new,1,250,Mercado Libre,202201,
1,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614566510,Maquina Algodón De Azúcar Comercial Accesorios,new,1,530,Mercado Libre,202201,
2,celinabatista05@outlook.com,BACE1960090,BATISTA,CELINA,NaN,DNI,06703964,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614604886,Máquina De Palomitas Oster Fpstpp7310 Roja 370...,new,1,86,Mercado Libre,202201,
3,luzmarlenetorrescoronado@gmail.com,LUZMARLENETORRESCORONADO,TORRES CORONADO,LUZ MARLENE,NaN,DNI,08001268,ZIP.,NaN,NaN,...,Level 3 Suplementos,Level 4 Level 3 Suplementos,614287436,* Prom Ago * Omega-3 1000mg - 180 Softgels Spr...,new,1,90,Mercado Libre,202201,
4,celinabatista06@outlook.com,BACE5517635,BATISTA,CELINA,NaN,DNI,16617381,ZIP.,NaN,NaN,...,Otros Maquillajes,Level 4 Otros Maquillajes,614533978,"Bon Bon Viktor & Rolf 90ml Nuevo, Sellado, Ori...",new,1,165,Mercado Libre,202201,
5,celinabatista04@outlook.com,BACE4599176,BATISTA,CELINA,NaN,DNI,19893998,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614572995,Licuadora Oster Xpert Blstvb-pmc-013 Negro C/rojo,new,1,375,Mercado Libre,202201,
6,celinabatista04@outlook.com,BACE4599176,BATISTA,CELINA,NaN,DNI,19893998,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614547008,Bocina Melo Dsp1560d 115v,new,1,285,Mercado Libre,202201,
7,celinabatista03@outlook.com,BACE3783927,BATISTA,CELINA,NaN,DNI,19980186,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614527442,Kit De Multiherramienta Wave+black Con Accesor...,new,1,201,Mercado Libre,202201,
8,celinabatista03@outlook.com,BACE3783927,BATISTA,CELINA,NaN,DNI,19980186,ZIP.,NaN,NaN,...,Level 3 Otros,Level 4 Level 3 Otros,614572959,Ejercitador De Piernas Power Legs Control De I...,new,2,485,Mercado Libre,202201,
9,valentinalaunder01@outlook.com,VALENTINALAUNDER,LAUNDER,VALENTINA,NaN,DNI,25548372,ZIP.,NaN,NaN,...,Otros,Level 4 Otros,613603629,Ejercitador De Piernas Power Legs Control De I...,new,1,218,Mercado Libre,202201,
10,valentinalaunder01@outlook.com,VALENTINALAUNDER,LAUNDER,VALENTINA,NaN,DNI,25548372,ZIP.,NaN,NaN,...,Otros,Level 4 Otros,613642163,Eliptica Motorizada Compacta Sit Fit Elliptica...,new,2,387,Mercado Libre,202201,
11,valentinalaunder01@outlook.com,VALENTINALAUNDER,LAUNDER,VALENTINA,NaN,DNI,25548372,ZIP.,NaN,NaN,...,Otros,Level 4 Otros,613431233,Banco Pesas Flybird Profesional Gym Ajustable ...,new,1,155,Mercado Libre,202201,
12,valentinalaunder01@outlook.com,VALENTINALAUNDER,LAUNDER,VALENTINA,NaN,DNI,25548372,ZIP.,NaN,NaN,...,Otros,Level 4 Otros,613642168,"Bicicleta Estática Spinning 13kg, Conectividad...",new,1,269,Mercado Libre,202201,
13,monsonlewse93@gmail.com,AMANDOFALCLUCENA,LUCENA,AMANDO FALCO,NaN,DNI,43667023,ZIP.,NaN,NaN,...,Level 3 Celulares y Smartphones,Level 4 Level 3 Celulares y Smartphones,613993177,Apple iPhone 13 Mini 128gb Nuevos Sellados Col...,new,1,2759,Mercado Libre,202201,
14,deoemily6@gmail.com,DELIAANGULOGRATE,GARATE,DELIA ANGULO,NaN,DNI,43667032,ZIP.,NaN,NaN,...,Aires Acondicionados,Level 4 Aires Acondicionados,614896921,Aire Acondicionado LG Inverter - 12.000 Btu,new,1,1500,Mercado Libre,202201,
15,apelhossain66662@gmail.com,JONATANATOCHE,ATOCHE,JONATAN,NaN,DNI,43667036,ZIP.,NaN,NaN,...,Refrigeradoras,Level 4 Refrigeradoras,608188501,Refrigerador Samsung Family Hub Rs27t5561 Blac...,new,1,4800,Mercado Libre,202201,
16,jluise713@gmail.com,MNICAFUENTEVENDRELL,VENDRELL,MONICA FUENTE,NaN,DNI,43667043,ZIP.,NaN,NaN,...,Level 3 Celulares y Smartphones,Level 4 Level 3 Celulares y Smartphones,613635813,Samsung Galaxy S22 Ultra 256gb 12gb Dual Sim N...,new,1,3999,Mercado Libre,202201,
17,presstonluise399@gmail.com,JAVIERIZAGUIRREESTVEZ,ESTEVEZ,JAVIER IZAGUIRRE,NaN,DNI,43667593,ZIP.,NaN,NaN,...,Level 3 Celulares y Smartphones,Level 4 Level 3 Celulares y Smartphones,613635810,Apple iPhone 13 Mini 128gb Nuevos Sellados Col...,new,1,2759,Mercado Libre,202201,
18,zdeering04@gmail.com,MOIS2803138,MONTERO,ISABELA,NaN,DNI,43667634,ZIP.,NaN,NaN,...,Level 3 Celulares y Smartphones,Level 4 Level 3 Celulares y Smartphones,612888043,Samsung Galaxy A53 5g 256gb 8gb Ram Dual Sim N...,new,1,959,Mercado Libre,202201,
19,arorazenin66@gmail.com,LUCABUSTOSLUCABUSTOS,LUCIA BUSTOS,LUCIA BUSTOS,NaN,DNI,43667893,ZIP.,NaN,NaN,...,Refrigeradoras,Level 4 Refrigeradoras,615052738,Refrigeradora Samsung Family Hub Rs27t5561 Mon...,new,1,4400,Mercado Libre,202201,

### CONSOLIDAR

In [70]:
df4 = df3.groupby(['CUS_CUST_DOC_TYPE',
                   'CUS_CUST_DOC_NUMBER',
                   'Periodo','CUS_NICKNAME',
                   'CUS_EMAIL','CEL_LIMPIO',
                   'CAT_CATEG_NAME_L1'], as_index=False).agg({
    'ORD_ITEM_QTY':sum,
    'ORD_TOTAL_AMOUNT':sum})

 
df4 = df3.groupby(['CUS_CUST_DOC_TYPE','CUS_CUST_DOC_NUMBER','Periodo','CUS_NICKNAME'], as_index=False).agg({'CUS_EMAIL':list,
                                                                    'CEL_LIMPIO':list,
                                                                         'CAT_CATEG_NAME_L1':list,           
                                                                    'ORD_ITEM_QTY':sum,
                                                                   'ORD_TOTAL_AMOUNT':sum})
df4.head()
#		ITE_ITEM_QUANTITY_AVAILABLE

### CREATING REPORT

In [71]:
df4.head(5)

,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,Periodo,CUS_NICKNAME,CUS_EMAIL,CEL_LIMPIO,CAT_CATEG_NAME_L1,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT
0,DNI,00001623,202201,ARYE3369011,yenearteagagamez@gmail.com,955320520,Industrias y Oficinas,1,1000
1,DNI,00004678,202201,SILVIAPATRICIATAVARAZAPATA,silviatavaraz@gmail.com,981573231,Belleza y Cuidado Personal,2,130
2,DNI,00014470,202201,COMPRAVENTACOMERCIO,urbano.damary.j@gmail.com,973193569,Ropa y Accesorios,2,50
3,DNI,00017480,202201,SKYS_MUSIC,skysmusic1@gmail.com,,Cámaras y Accesorios,1,1271
4,DNI,00017480,202201,SKYS_MUSIC,skysmusic1@gmail.com,,"Electrónica, Audio y Video",1,550

def quitarnulos(lista):
    lista = list(filter(None,lista))
    return lista

#eliminar duplicados
df4['CUS_EMAIL'] = df4.apply(lambda x: list(set(x['CUS_EMAIL'])),axis = 1)
df4['CEL_LIMPIO'] = df4.apply(lambda x: list(set(x['CEL_LIMPIO'])) ,axis = 1)
df4['CAT_CATEG_NAME_L1'] = df4.apply(lambda x: list(set(x['CAT_CATEG_NAME_L1'])),axis = 1)
#quitar nulos
df4['CEL_LIMPIO'] = df4.apply(lambda x: quitarnulos(x['CEL_LIMPIO']) ,axis = 1)

#agregar cantidad
df4['N_EMAIL'] = df4.apply(lambda x: len(x['CUS_EMAIL']),axis = 1)
df4['N_CEL'] = df4.apply(lambda x: 0 if len(x['CEL_LIMPIO'])== 0 else len(x['CEL_LIMPIO']) ,axis = 1)
df4['N_CAT'] = df4.apply(lambda x: len(x['CAT_CATEG_NAME_L1']),axis = 1)

#convertir a strings
df4['CEL_LIMPIO'] = df4.apply(lambda x: ','.join(x['CEL_LIMPIO']),axis = 1)
df4['CUS_EMAIL'] = df4.apply(lambda x: ','.join(x['CUS_EMAIL']),axis = 1)
df4['CAT_CATEG_NAME_L1'] = df4.apply(lambda x: ','.join(x['CAT_CATEG_NAME_L1']),axis = 1)

In [72]:
df4.head(1)

,CUS_CUST_DOC_TYPE,CUS_CUST_DOC_NUMBER,Periodo,CUS_NICKNAME,CUS_EMAIL,CEL_LIMPIO,CAT_CATEG_NAME_L1,ORD_ITEM_QTY,ORD_TOTAL_AMOUNT
0,DNI,00001623,202201,ARYE3369011,yenearteagagamez@gmail.com,955320520,Industrias y Oficinas,1,1000

In [73]:
df4.columns = df4.columns.str.replace('CUS_CUST_DOC_TYPE', 'TIPO DE DOCUMENTO DEL VENDEDOR')
df4.columns = df4.columns.str.replace('CUS_CUST_DOC_NUMBER', 'NUMERO DE DOCUMENTO DEL VENDEDOR')
df4.columns = df4.columns.str.replace('CEL_LIMPIO', 'NUMERO DE TELEFONO DE CONTACTO')
df4.columns = df4.columns.str.replace('CUS_EMAIL', 'CORREO ELECTRONICO')
df4.columns = df4.columns.str.replace('ORD_ITEM_QTY', 'CANTIDAD DE PRODUCTOS VENDIDOS')
df4.columns = df4.columns.str.replace('ORD_TOTAL_AMOUNT', 'VENTA IMPUTADA S/')
df4.columns = df4.columns.str.replace('CUS_NICKNAME', 'USUARIO')
df4.columns = df4.columns.str.replace('Periodo', 'PERIODO TRIBUTARIO MENSUAL')
df4.head(5)

,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,PERIODO TRIBUTARIO MENSUAL,USUARIO,CORREO ELECTRONICO,NUMERO DE TELEFONO DE CONTACTO,CAT_CATEG_NAME_L1,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
0,DNI,00001623,202201,ARYE3369011,yenearteagagamez@gmail.com,955320520,Industrias y Oficinas,1,1000
1,DNI,00004678,202201,SILVIAPATRICIATAVARAZAPATA,silviatavaraz@gmail.com,981573231,Belleza y Cuidado Personal,2,130
2,DNI,00014470,202201,COMPRAVENTACOMERCIO,urbano.damary.j@gmail.com,973193569,Ropa y Accesorios,2,50
3,DNI,00017480,202201,SKYS_MUSIC,skysmusic1@gmail.com,,Cámaras y Accesorios,1,1271
4,DNI,00017480,202201,SKYS_MUSIC,skysmusic1@gmail.com,,"Electrónica, Audio y Video",1,550

In [74]:
len(df4)

37303

In [75]:
principal = df4[['USUARIO',
                 'PERIODO TRIBUTARIO MENSUAL',
                 'TIPO DE DOCUMENTO DEL VENDEDOR',
                  'NUMERO DE DOCUMENTO DEL VENDEDOR',
                  'NUMERO DE TELEFONO DE CONTACTO',
                  'CORREO ELECTRONICO',
                 'CANTIDAD DE PRODUCTOS VENDIDOS',
                 'VENTA IMPUTADA S/']]

principal.head(1)

,USUARIO,PERIODO TRIBUTARIO MENSUAL,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
0,ARYE3369011,202201,DNI,00001623,955320520,yenearteagagamez@gmail.com,1,1000

In [76]:
#principal[(principal['CORREO ELECTRONICO'] == 'ml.peru@bluediamondinnovation.com')]
principal[(principal['CORREO ELECTRONICO']=='ml.peru@bluediamondinnovation.com') & (principal['PERIODO TRIBUTARIO MENSUAL']==202201)]

,USUARIO,PERIODO TRIBUTARIO MENSUAL,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
36250,BLUE-DIAMOND-PERU,202201,RUC,20606185775,,ml.peru@bluediamondinnovation.com,4,3306
36251,BLUE-DIAMOND-PERU,202201,RUC,20606185775,,ml.peru@bluediamondinnovation.com,243,686288
36252,BLUE-DIAMOND-PERU,202201,RUC,20606185775,,ml.peru@bluediamondinnovation.com,66,49054
36253,BLUE-DIAMOND-PERU,202201,RUC,20606185775,,ml.peru@bluediamondinnovation.com,1,209
36254,BLUE-DIAMOND-PERU,202201,RUC,20606185775,,ml.peru@bluediamondinnovation.com,1,719

In [77]:
df3["NOMBRES Y APELLIDOS DEL VENDEDOR"] = df3["CUS_FIRST_NAME"].astype(str)  +" "+ df3["CUS_LAST_NAME"].astype(str)
df3.columns = df3.columns.str.replace('Plataforma', 'PLATAFORMA INFORMANTE')
df3.columns = df3.columns.str.replace('CUS_NICKNAME', 'USUARIO')
df3.columns = df3.columns.str.replace('CUS_BRAND_NAME', 'RAZON SOCIAL DEL VENDEDOR')

df_total = df3[[  'PLATAFORMA INFORMANTE',
                  'USUARIO',
                  'NOMBRES Y APELLIDOS DEL VENDEDOR',
                  'RAZON SOCIAL DEL VENDEDOR']]
df_total.head(1)

D:\Usuarios\dcantorin\AppData\Local\Temp\ipykernel_6776\4173807781.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["NOMBRES Y APELLIDOS DEL VENDEDOR"] = df3["CUS_FIRST_NAME"].astype(str)  +" "+ df3["CUS_LAST_NAME"].astype(str)

,PLATAFORMA INFORMANTE,USUARIO,NOMBRES Y APELLIDOS DEL VENDEDOR,RAZON SOCIAL DEL VENDEDOR
0,Mercado Libre,LIMACHECCOSIFRESSIA,FRESSIA LIMACHE CCOSI,NaN

In [78]:
mercado= principal.merge(df_total, on='USUARIO', how='left')
len(mercado)

1812176

In [79]:
df_total = mercado[['PERIODO TRIBUTARIO MENSUAL',
                  'PLATAFORMA INFORMANTE',
                  'USUARIO',
                  'NOMBRES Y APELLIDOS DEL VENDEDOR',
                  'RAZON SOCIAL DEL VENDEDOR',
                  'TIPO DE DOCUMENTO DEL VENDEDOR',
                  'NUMERO DE DOCUMENTO DEL VENDEDOR',
                  'NUMERO DE TELEFONO DE CONTACTO',
                  'CORREO ELECTRONICO',
                  'CANTIDAD DE PRODUCTOS VENDIDOS',
                  'VENTA IMPUTADA S/']]


#1	PERIODO TRIBUTARIO MENSUAL
#2	PLATAFORMA INFORMANTE
#3	USUARIO
#4	NOMBRES Y APELLIDOS DEL VENDEDOR
#5	RAZON SOCIAL DEL VENDEDOR
#6	TIPO DE DOCUMENTO DEL VENDEDOR
#7	NUMERO DE DOCUMENTO DEL VENDEDOR
#8	NUMERO DE TELEFONO DE CONTACTO
#9	CORREO ELECTRONICO
#10	CANTIDAD DE PRODUCTOS VENDIDOS
#11	VENTA IMPUTADA S/

In [80]:
df_total = df_total.drop_duplicates()
df_total

,PERIODO TRIBUTARIO MENSUAL,PLATAFORMA INFORMANTE,USUARIO,NOMBRES Y APELLIDOS DEL VENDEDOR,RAZON SOCIAL DEL VENDEDOR,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
0,202201,Mercado Libre,ARYE3369011,YENETSIS ARTEAGA,YENETSIS ARTEAGA,DNI,00001623,955320520,yenearteagagamez@gmail.com,1,1000
1,202201,Mercado Libre,SILVIAPATRICIATAVARAZAPATA,SILVIA PATRICIA TAVARA ZAPATA,SILVIA PATRICIA TAVARA ZAPATA,DNI,00004678,981573231,silviatavaraz@gmail.com,2,130
2,202201,Mercado Libre,COMPRAVENTACOMERCIO,DARWIN PALMA,NaN,DNI,00014470,973193569,urbano.damary.j@gmail.com,2,50
3,202201,Mercado Libre,SKYS_MUSIC,ANTONIO ARCANA,NaN,DNI,00017480,,skysmusic1@gmail.com,1,1271
5,202201,Mercado Libre,SKYS_MUSIC,ANTONIO ARCANA,NaN,DNI,00017480,,skysmusic1@gmail.com,1,550
...,...,...,...,...,...,...,...,...,...,...,...
1812007,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,RUC,20610308652,993928936,nan,81,5291
1812049,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,RUC,20610308652,993928936,nan,2,260
1812091,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,RUC,20610308652,993928936,nan,4,113
1812133,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,RUC,20610308652,993928936,nan,2,249
1812175,202201,Mercado Libre,ARMOUR BODY,nan nan,ARMOUR BODY PERU SAC,RUC,20610313834,987928142,nan,2,184

In [81]:
prueba = df_total[(df_total['CORREO ELECTRONICO'] == 'ml.peru@bluediamondinnovation.com')]
prueba

,PERIODO TRIBUTARIO MENSUAL,PLATAFORMA INFORMANTE,USUARIO,NOMBRES Y APELLIDOS DEL VENDEDOR,RAZON SOCIAL DEL VENDEDOR,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
1695025,202201,Mercado Libre,BLUE-DIAMOND-PERU,nan nan,AMAZE PERU EIRL,RUC,20606185775,,ml.peru@bluediamondinnovation.com,4,3306
1695121,202201,Mercado Libre,BLUE-DIAMOND-PERU,nan nan,AMAZE PERU EIRL,RUC,20606185775,,ml.peru@bluediamondinnovation.com,243,686288
1695217,202201,Mercado Libre,BLUE-DIAMOND-PERU,nan nan,AMAZE PERU EIRL,RUC,20606185775,,ml.peru@bluediamondinnovation.com,66,49054
1695313,202201,Mercado Libre,BLUE-DIAMOND-PERU,nan nan,AMAZE PERU EIRL,RUC,20606185775,,ml.peru@bluediamondinnovation.com,1,209
1695409,202201,Mercado Libre,BLUE-DIAMOND-PERU,nan nan,AMAZE PERU EIRL,RUC,20606185775,,ml.peru@bluediamondinnovation.com,1,719

In [82]:
df_total['TIPO DE DOCUMENTO DEL VENDEDOR'] = df_total['TIPO DE DOCUMENTO DEL VENDEDOR'].replace(['RUC'], '6')
df_total['TIPO DE DOCUMENTO DEL VENDEDOR'] = df_total['TIPO DE DOCUMENTO DEL VENDEDOR'].replace(['C.E'], '4')
df_total['TIPO DE DOCUMENTO DEL VENDEDOR'] = df_total['TIPO DE DOCUMENTO DEL VENDEDOR'].replace(['DNI'], '1')
df_total

,PERIODO TRIBUTARIO MENSUAL,PLATAFORMA INFORMANTE,USUARIO,NOMBRES Y APELLIDOS DEL VENDEDOR,RAZON SOCIAL DEL VENDEDOR,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
0,202201,Mercado Libre,ARYE3369011,YENETSIS ARTEAGA,YENETSIS ARTEAGA,1,00001623,955320520,yenearteagagamez@gmail.com,1,1000
1,202201,Mercado Libre,SILVIAPATRICIATAVARAZAPATA,SILVIA PATRICIA TAVARA ZAPATA,SILVIA PATRICIA TAVARA ZAPATA,1,00004678,981573231,silviatavaraz@gmail.com,2,130
2,202201,Mercado Libre,COMPRAVENTACOMERCIO,DARWIN PALMA,NaN,1,00014470,973193569,urbano.damary.j@gmail.com,2,50
3,202201,Mercado Libre,SKYS_MUSIC,ANTONIO ARCANA,NaN,1,00017480,,skysmusic1@gmail.com,1,1271
5,202201,Mercado Libre,SKYS_MUSIC,ANTONIO ARCANA,NaN,1,00017480,,skysmusic1@gmail.com,1,550
...,...,...,...,...,...,...,...,...,...,...,...
1812007,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,6,20610308652,993928936,nan,81,5291
1812049,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,6,20610308652,993928936,nan,2,260
1812091,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,6,20610308652,993928936,nan,4,113
1812133,202201,Mercado Libre,DYMNAILSTORE,nan nan,D & M NAIL STORE S.A.C.,6,20610308652,993928936,nan,2,249
1812175,202201,Mercado Libre,ARMOUR BODY,nan nan,ARMOUR BODY PERU SAC,6,20610313834,987928142,nan,2,184

In [83]:
df_consolidado = df_total.drop_duplicates()
len(df_consolidado)

38301

In [84]:
df_consolidado.to_csv('ML_2022_S2.csv',sep='|', encoding='utf-8', index=False)
df_consolidado.to_excel('ML_2022_S2'+'.xlsx', encoding='utf-8', index=False )

In [85]:
path = r'D:\JUPYTER\CODIGO_REQUERIMIENTOS\CSV_MARKETS\2022\2022_02' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0, encoding='utf-8',sep='|', on_bad_lines='skip')
    li.append(df)

df_marketplaces = pd.concat(li, axis=0, ignore_index=True)
df_marketplaces
##### aquí termina ######

,PERIODO TRIBUTARIO MENSUAL,PLATAFORMA INFORMANTE,USUARIO,NOMBRES Y APELLIDOS DEL VENDEDOR,RAZON SOCIAL DEL VENDEDOR,TIPO DE DOCUMENTO DEL VENDEDOR,NUMERO DE DOCUMENTO DEL VENDEDOR,NUMERO DE TELEFONO DE CONTACTO,CORREO ELECTRONICO,CANTIDAD DE PRODUCTOS VENDIDOS,VENTA IMPUTADA S/
0,202101,Linio,faskmperu@outlook.com,SHEYLLA DAYANNE LOPEZ COVE\u00d1AS,FASKM PERU SAC,6.0,20609537974,94275-8432,faskmperu@outlook.com,1.0,9.200000
1,202101,Linio,importmisha64@gmail.com,Melissa Purizaca Llajaruna,MISHA IMPORT S.A.C,6.0,20609198916,01-4291247,importmisha64@gmail.com,4.0,106.700003
2,202101,Linio,jonllerenaz@gmail.com|Jonathan Llerena Zapata|...,NaN,NaN,NaN,NaN,NaN,jonllerenaz@gmail.com|Jonathan Llerena Zapata|...,NaN,NaN
3,202101,Linio,dperez@mdtechperu.com,FRANCIS ANN MC KAY DIEZ CANSECO,MD TECH S.A.,6.0,20510352913,01-2221929,dperez@mdtechperu.com,1.0,28.500000
4,202101,Linio,mandiarteperu@gmail.com,GALVEZ ZU\u00d1IGA DIANA ELIZABETH,GALVEZ ZUÑIGA DIANA ELIZABETH,6.0,10406412461,51-955874490,mandiarteperu@gmail.com,2.0,165.000000
...,...,...,...,...,...,...,...,...,...,...,...
29027,202201,Mercado Libre,CMAUDIOVISUALPERU,NaN,NaN,6.0,20610101071,992710720.0,cmav.mlibre@gmail.com,383.0,424290.000000
29028,202201,Mercado Libre,DOMOTICHOME.PERU,NaN,NaN,6.0,20610134379,938334925.0,ricardo_goodheart_14@hotmail.com,88.0,8618.000000
29029,202201,Mercado Libre,ROEN STORE,NaN,NaN,6.0,20610279407,NaN,NaN,40.0,4768.000000
29030,202201,Mercado Libre,DYMNAILSTORE,NaN,NaN,6.0,20610308652,993928936.0,NaN,91.0,6109.000000
29031,202201,Mercado Libre,ARMOUR BODY,NaN,NaN,6.0,20610313834,987928142.0,NaN,2.0,184.000000

In [88]:
path_f =r'D:\jupyter\codigo_requerimientos\csv_markets'
df_marketplaces.to_csv(path_f +'\\'+ 'MARKETPLACE_2022_02.csv',sep='|', encoding='utf-8', index=False)
df_marketplaces.to_csv(path_f +'\\'+ 'MARKETPLACE_2022_02.txt',sep='|', encoding='utf-8', index=False)
df_marketplaces.to_excel(path_f +'\\'+ 'MARKETPLACE_2022_02'+'.xlsx', encoding='utf-8', index=False )